### ISSUE TITLE
get_user_apps happened crash when user does not  have apps.

### ISSUE THREAD

**Issue by kk2170** [onelogin/onelogin-ruby-sdk#10]
# Description
When I use get_user_apps for all user, it is crashed by the user who does not have apps.
This crash occur by `GET_APPS_FOR_USER_URL` response which include `"data"=>[[]]`.

# Log
```
/Users/usr0200590/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/bundler/gems/onelogin-ruby-sdk-9cf31c87b2ef/lib/onelogin/api/models/app.rb:11:in `[]': no implicit conversion of String into Integer (TypeError)
	from /Users/usr0200590/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/bundler/gems/onelogin-ruby-sdk-9cf31c87b2ef/lib/onelogin/api/models/app.rb:11:in `initialize'
	from /Users/usr0200590/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/bundler/gems/onelogin-ruby-sdk-9cf31c87b2ef/lib/onelogin/api/cursor.rb:32:in `new'
	from /Users/usr0200590/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/bundler/gems/onelogin-ruby-sdk-9cf31c87b2ef/lib/onelogin/api/cursor.rb:32:in `block in each'
	from /Users/usr0200590/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/bundler/gems/onelogin-ruby-sdk-9cf31c87b2ef/lib/onelogin/api/cursor.rb:30:in `each'
	from /Users/usr0200590/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/bundler/gems/onelogin-ruby-sdk-9cf31c87b2ef/lib/onelogin/api/cursor.rb:30:in `each'
	from /Users/usr0200590/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/bundler/gems/onelogin-ruby-sdk-9cf31c87b2ef/lib/onelogin/api/cursor.rb:43:in `each'
	from /Users/usr0200590/RubymineProjects/util/test.rb:12:in `block in <top (required)>'
	from /Users/usr0200590/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/bundler/gems/onelogin-ruby-sdk-9cf31c87b2ef/lib/onelogin/api/cursor.rb:32:in `block in each'
	from /Users/usr0200590/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/bundler/gems/onelogin-ruby-sdk-9cf31c87b2ef/lib/onelogin/api/cursor.rb:30:in `each'
	from /Users/usr0200590/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/bundler/gems/onelogin-ruby-sdk-9cf31c87b2ef/lib/onelogin/api/cursor.rb:30:in `each'
	from /Users/usr0200590/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/bundler/gems/onelogin-ruby-sdk-9cf31c87b2ef/lib/onelogin/api/cursor.rb:43:in `each'
	from /Users/usr0200590/RubymineProjects/util/test.rb:11:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

# How To Repeat
```
require 'onelogin'
require 'yaml'

api_key = YAML.load_file('api_key.yml')
client = OneLogin::Api::Client.new(
    client_secret: api_key['onelogin']['client_secret'],
    client_id: api_key['onelogin']['client_id'],
    max_results: 50000
)

client.get_users.each do |user| # You need user who does not have any apps. 
  client.get_user_apps(user.id).each do |app|
    p app
  end
end

```

# Suggestion fix
`GET_APPS_FOR_USER_URL` API should not response `"data"=>[[]]`.   I guess `"data" => []` is better.

## Anyway workaround
https://github.com/kk2170/onelogin-ruby-sdk/commit/3b78e72223b542f6642398968181957e45c237bb

**Comment by pitbulk** [comment]
@richet what do you think about that solution?

**Comment by richet** [comment]
Fixed. Thanks for the heads up.

**Comment by kk2170** [comment]
Thanks!
