### ISSUE TITLE
NoMethodError when using `get_user_apps` of `Client`.

### ISSUE THREAD

**Issue by kk2170** [onelogin/onelogin-ruby-sdk#8]
# Description
When I call `get_user_apps` in my code, it occur NoMethodError. 

# Log
```
/Users/kk2170/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/onelogin-1.0.0/lib/onelogin/api/cursor.rb:77:in `results_remaining': undefined method `-' for nil:NilClass (NoMethodError)
	from /Users/kk2170/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/onelogin-1.0.0/lib/onelogin/api/cursor.rb:60:in `fetch_next_page'
	from /Users/kk2170/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/onelogin-1.0.0/lib/onelogin/api/cursor.rb:41:in `each'
	from /Users/kk2170/RubymineProjects/util/main.rb:51:in `block in <top (required)>'
	from /Users/kk2170/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/onelogin-1.0.0/lib/onelogin/api/cursor.rb:32:in `block in each'
	from /Users/kk2170/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/onelogin-1.0.0/lib/onelogin/api/cursor.rb:30:in `each'
	from /Users/kk2170/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/onelogin-1.0.0/lib/onelogin/api/cursor.rb:30:in `each'
	from /Users/kk2170/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/onelogin-1.0.0/lib/onelogin/api/cursor.rb:43:in `each'
	from /Users/kk2170/RubymineProjects/util/main.rb:50:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

# How to repeat

```
client = OneLogin::Api::Client.new(
    client_secret: 'using_valid_secret',
    client_id: 'using_valid_id',
    max_results: 50000
)

users = client.get_users
users.each do |user|
  client.get_user_apps(user.id).each do |app|
    p app
  end
end
```

# Suggested fix
https://github.com/kk2170/onelogin-ruby-sdk/commit/7018f63acce2418f8b18b82314ec8074fbc8c0c7

**Comment by pitbulk** [comment]
Fixed with your suggestion.

**Comment by kk2170** [comment]
Thanks!
As I confirmed it was fixed, so I close this issue.
